name: watch_flow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get: ^4.6.6
  google_generative_ai: ^0.4.6
  path: ^1.9.0
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+2
  url_launcher: ^6.3.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_lints: ^4.0.0
  icons_launcher: ^3.0.0
  flutter_test:
    sdk: flutter
# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/icon/launcher_icon.png"  # مسار أيقونة التطبيق
#   adaptive_icon_background: "#FFFFFF"        # لون الخلفية للأيقونات المتكيفة (خاص بأندرويد)
#   adaptive_icon_foreground: "assets/images/icon/launcher_icon.png"  # الطبقة الأمامية للأيقونة المتكيفة
icons_launcher:
  platforms:
    android:
      enable: true
    ios:
      enable: true
  image_path: assets/images/icon/icone.jpg
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/icon/icone.jpg
  assets:
    - assets/images/
    - assets/images/icon/
flutter:
  uses-material-design: true
